#!/bin/bash
#https://medium.com/weekly-webtips/create-a-pre-commit-git-hook-for-eslint-45decfb0357c
cd "$(git rev-parse --show-toplevel)"
ESLINT_CLIENT="client/node_modules/.bin/eslint"
ESLINT_SERVER="server/node_modules/.bin/eslint"
pwd

if [[ ! -x "$ESLINT_CLIENT" ]]; then
  printf "\t\033[41mPlease install ESlint in client\033[0m (npm install eslint)\n"
  exit 1
fi

if [[ ! -x "$ESLINT_SERVER" ]]; then
  printf "\t\033[41mPlease install ESlint in your SERVER, unless SERVER hasn't been setup\033[0m \n"
  # exit 1
fi

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"))

echo "ESLint'ing ${#STAGED_FILES[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$ESLINT_CLIENT "${STAGED_FILES[@]}" --fix

if [[  -x "$ESLINT_SERVER" ]]; then
  $ESLINT_SERVER "${STAGED_FILES[@]}" --fix
fi

ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?