export const genders = [
  'Female',
  'Male',
  'Non-binary',
  'Prefer not to say',
  'Other',
];

export const experienceLevels = [
  'Beginner',
  'Intermediate',
  'Advanced',
];

export const healthConditionsAndInjuriesOptions = [
  'Heart disease',
  'Asthma',
  'Diabetes',
  'High blood pressure',
  'Arthritis',
  'Osteoporosis',
  'Pregnancy',
  'Obesity',
  'Chronic pain',
  'Anxiety or depression',
  'Joint injuries (e.g., sprains, strains)',
  'Back pain',
  'Knee pain',
  'Shoulder impingement',
  'Tendonitis',
  'Rotator cuff injury',
  'Plantar fasciitis',
  'Carpal tunnel syndrome',
  'Sports-related concussions',
  'Hamstring strain',
  'Shin splints',
  'IT band syndrome',
  'Golfer\'s elbow',
  'Tennis elbow',
  'Pulled muscles',
];

export const dietaryRestrictionsOptions = [
  'Vegetarian',
  'Vegan',
  'Gluten-free',
  'Dairy-free',
  'Nut-free',
  'Shellfish-free',
  'Pescatarian',
  'Kosher',
  'Halal',
  'Low-carb',
  'Low-fat',
  'Sugar-free',
  'Paleo',
  'Whole30',
  'FODMAP',
];

export const allergiesIntolerancesOptions = [
  'Milk',
  'Eggs',
  'Peanuts',
  'Tree nuts',
  'Wheat',
  'Soy',
  'Fish',
  'Shellfish',
  'Sesame seeds',
  'Barley',
  'Rye',
  'Oats',
  'Lactose',
  'Sulphites',
  'Almonds',
  'Cashews',
  'Walnuts',
  'Pecans',
  'Hazelnuts',
  'Pistachios',
  'Brazil nuts',
  'Macadamia nuts',
  'Soybeans',
  'Eggs',
  'Sesame seeds',
];

export const weeklyAvailabilityOptions = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
